# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('self', '自聊'), ('user', '单聊'), ('group', '群聊')], max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=8)),
                ('msg_id', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('init_id', models.BigIntegerField(default=0)),
                ('cur_id', models.BigIntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='xchat.Chat')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('msg_id', models.BigIntegerField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('msg', models.TextField()),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'xchat_message',
            },
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('chat_id', 'msg_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('chat', 'user')]),
        ),
    ]
