# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('self', '自聊'), ('user', '单聊'), ('users', '讨论组'), ('group', '群聊'), ('cs', '客服'), ('room', '房间')], max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=8)),
                ('msg_id', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=32)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('cur_id', models.BigIntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='xchat.Chat')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=8)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(default=0)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xchat.Chat')),
                ('room', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='xchat.Room')),
            ],
            options={
                'verbose_name': 'RoomChat',
                'verbose_name_plural': 'RoomChats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='roomchat',
            unique_together=set([('room', 'area')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('chat', 'user')]),
        ),
    ]
