# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='init_id',
        ),
    ]
