# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 03:44
from __future__ import unicode_literals

from django.db import models, migrations


def add_init_chats(apps, schema_editor):
    Chat = apps.get_model("xchat", "Chat")

    c = Chat(type='group', title='测试', tag='test')
    c.save()
    c.members.create(user='test:test')
    c.members.create(user='test:webee')


def add_qq_grd_room(apps, schema_editor):
    Room = apps.get_model("xchat", "Room")
    Chat = apps.get_model("xchat", "Chat")

    r = Room(title='广场', tag='qq_grd')
    r.save()

    for i in range(20):
        c = Chat(type='room', title=str(r.id), tag='_room')
        c.save()

        r.chats.create(area=i, chat=c)


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_init_chats),
        migrations.RunPython(add_qq_grd_room),
    ]

