# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0002_auto_20160519_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='tag',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
