# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0003_chat_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exit_msg_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunSQL('alter table xchat_member alter exit_msg_id set default 0'),
        migrations.AddField(
            model_name='member',
            name='is_exited',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL('alter table xchat_member alter is_exited set default false'),
        migrations.AlterField(
            model_name='chat',
            name='ext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
