# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0003_auto_20160607_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=32)),
                ('dev', models.CharField(max_length=32)),
                ('dev_id', models.CharField(max_length=256)),
                ('info', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device info',
                'verbose_name_plural': 'Device infos',
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterUniqueTogether(
            name='deviceinfo',
            unique_together=set([('user', 'dev', 'dev_id')]),
        ),
    ]
