# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0004_auto_20160722_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dnd',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL('alter table xchat_member alter dnd set default false', reverse_sql=''),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('self', '自聊'), ('user', '单聊'), ('users', '讨论组'), ('group', '群组'), ('cs', '客服'), ('room', '房间')], max_length=10),
        ),
    ]
