# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0005_auto_20160609_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='xchat.Room'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('self', '自聊'), ('user', '单聊'), ('group', '群聊'), ('cs', '客服')], max_length=10),
        ),
    ]
