# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0005_auto_20160810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_msg_ts',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), editable=False),
        ),
    ]
