# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0006_auto_20160613_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 14, 3, 11, 9, 983558, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
