# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0006_chat_last_msg_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='join_msg_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.RunSQL('alter table xchat_member alter join_msg_id set default 0', reverse_sql=''),
        migrations.AlterField(
            model_name='chat',
            name='msg_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('self', '自聊'), ('user', '单聊'), ('users', '讨论组'), ('group', '群组'), ('cs', '客服'), ('room', '房间')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='cur_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='exit_msg_id',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
