# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0007_auto_20161110_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='members_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
