# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0007_chat_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'RoomChat',
                'verbose_name_plural': 'RoomChats',
            },
        ),
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.AddField(
            model_name='roomchat',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xchat.Chat'),
        ),
        migrations.AddField(
            model_name='roomchat',
            name='room',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='xchat.Room'),
        ),
    ]
