# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0008_auto_20170113_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.CharField(db_index=True, default=None, max_length=32, null=True),
        ),
    ]
