# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0008_auto_20160614_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('self', '自聊'), ('user', '单聊'), ('group', '群聊'), ('room', '房间'), ('cs', '客服')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='roomchat',
            unique_together=set([('room', 'seq')]),
        ),
    ]
