# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchat', '0010_auto_20170207_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True),
        ),
    ]
